language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

script:
  - ./../Data/download_anno.sh
  - py.test test.py -v

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
    slack: cloudcv:gy3CGQGNXLwXOqVyzXGZfdea