language: python
sudo: false
python:
  - "2.7"


cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - cd Data
  - ./download_anno.sh
  - cd PythonEvaluationTools
  - py.test test.py -v

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
    slack: cloudcv:gy3CGQGNXLwXOqVyzXGZfdea