language: python
sudo: false
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - ./Data/download_anno.sh
  - py.test PythonEvaluationTools/test.py -v

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
    slack: cloudcv:gy3CGQGNXLwXOqVyzXGZfdea